import Head from "next/head";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import { Account } from "@klever/sdk";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="/kleverSDK/kleverSDKLoader.js"
        strategy="beforeInteractive"
      />
      <main className={styles.main}>
        <button
          onClick={() => {
            const account = new Account(
              "Your Address Here",
              "Your Private Key Here"
            );

            const transactionPayload = {
              receiver:
                "klv17e8zzgn73h6ehe3c6q9vlt77kuxk5euddmhymy5uhv2rhv0dc0nqlfp0ap",
              amount: 100,
            };

            account
              .sendTransfer(transactionPayload)
              .then((taa) => console.log(taa))
              .catch((err) => console.log(err));
          }}
        >
          Transfer
        </button>
      </main>
    </div>
  );
}
